### ISSUE TITLE
Does not work in ProxySpace

### ISSUE THREAD

**Issue by mantsar** [elgiano/nn.ar#2] opened 2023-07-04 14:20 UTC
Hi, thanks for this amazing implementation!! Works great however I get error while using proxyspace:

```
p = ProxySpace.push(s);
NN.load(\rave, "~/rave/percussion.ts");
NN(\rave).describe;
```
```
^^ ERROR: Message 'models' not understood.
```

**Comment by elgiano** [comment] 2023-07-13 11:50
Hey, thanks a lot for this report! It's actually a design problem.
I'm currently re-structuring the scsynth part, so I can't fix it really fast... but here is an idea if you want to fix it yourself in the meanwhile:

The problem is in NN.isNRT, which is currently implemented like this:
```supercollider
*isNRT { ^currentEnvironment[\nn_nrt].notNil }
```

as a temporary fix, we could change it to this:
```supercollider
*isNRT {
    ^currentEnvironment[\nn_nrt].notNil and: {
        currentEnvironment[\nn_nrt][\models].notNil
    }
}
```

Let me know how it works for you :)

**Comment by mantsar** [comment] 2023-07-21 14:08
@elgiano Tried with new update and it works great!

**Comment by elgiano** [comment] 2023-07-22 12:02
fixed in v.0.0.3-alpha

**Closed as completed by elgiano** 2023-07-22 12:02 UTC
